### ISSUE TITLE
Implement major improvements from silentarmy

### ISSUE THREAD

**Issue by kruisdraad** [maztheman/nheqminer#3]
Could you please insert this and build for windows and linux?

https://github.com/mbevand/silentarmy/

https://forum.z.cash/t/silentarmy-v5-2x-speedup-100-sol-s-on-amd-70-sol-s-on-nvidia/3580/1069?u=crosswire

Major 2× speedup
CPU usage down to zero
PCIe bandwidth reduced from 100 MB/s down to 500 kB/s per GPU.

You can expect:
* 102.0 sol/s with one R9 Nano
* 72.0 sol/s with one RX 480 8GB
* 64.0 sol/s with one GTX 1070

**Comment by maztheman** [comment]
Yes I will update this but it won't be for a bit since I'm away from my computer.  Looks very interesting!  Thanks for the heads up. I'll read up on the changes.

**Comment by maztheman** [comment]
But for linux I have no way of actually testing it..

**Comment by maztheman** [comment]
I have created a new release.

**Comment by kruisdraad** [comment]
not windows compiled?
