### ISSUE TITLE
TODO: Test Silent army v5 of a wide variety of devices

### ISSUE THREAD

**Issue by maztheman** [maztheman/nheqminer#5]
Discuss your results here

**Comment by kruisdraad** [comment]
Windows build please

**Comment by maztheman** [comment]
it is failing, i have to fix it up...

**Comment by maztheman** [comment]
If you have a 1070 or 1080 please test it:

https://github.com/maztheman/nheqminer/releases/tag/v0.4h

**Comment by drigger** [comment]
![image](https://cloud.githubusercontent.com/assets/2197585/20282049/20beb24e-aac4-11e6-85a5-14d6676dd257.png)

**Comment by drigger** [comment]
![image](https://cloud.githubusercontent.com/assets/2197585/20282128/6ecf4cbe-aac4-11e6-9330-d6751be99df9.png)

**Comment by maztheman** [comment]
try:
https://github.com/maztheman/nheqminer/releases/download/v0.4h/v0.4h_1070_plus.7z

i remove all the thread waiting..

**Comment by maztheman** [comment]
the v5 silent army doesnt seem to be too great when converted to CUDA :(, however It might just be the way its looping...i might be able to fix it

**Comment by drigger** [comment]
Hmm, w/ 0.4h_1070_plus this happens: ![image](https://cloud.githubusercontent.com/assets/2197585/20282557/40cddcb6-aac6-11e6-82c4-c75bd53756c6.png)  ;)
Just for the sake of comparison - this is what I get w/ the same 1080 on one of the original SA5 python ports for windows: ![image](https://cloud.githubusercontent.com/assets/2197585/20282362/7e53ee32-aac5-11e6-8026-f1957382bdc4.png)

**Comment by maztheman** [comment]
yeah there is some major issue with cuda and that code that was posted for opencl.  cuda keeps "timing" out when I try to do same kind of calls...I guess itll have to be a work in progress for now.

Ill post again when I see improvement with my GTX 650, which should then indicate some progress with 1080s, etc.

**Comment by maztheman** [comment]
I see from the author or silentarmy:

mbevand commented 2 days ago • edited
@tupieurods You are right. Didn't know shared atomics were not hardware implemented pre-Maxwell. That' s definitively the cause of the slowdown then, because this commit makes heavy use of shared atomics. I see no solution other than maintaining a 2nd separate version of input.cl specifically for pre-Maxwell Nvidia GPUs then.

**Comment by maztheman** [comment]
Well based off that guys message I reverted back to a more direct conversion, maybe itll work better:

https://github.com/maztheman/nheqminer/releases/download/v0.4h/v0.4h_MAXWEL_PLUS.7z

It was super slow on GTX 650 but looks like it will be because of the shared atomics

**Comment by drigger** [comment]
It gives me much higher I/s numbers + full GPU load, but no Sols, unfortunately =)
![image](https://cloud.githubusercontent.com/assets/2197585/20283428/151f9088-aaca-11e6-91b6-6337562a68e1.png)

**Comment by maztheman** [comment]
hmm wierd, i get 78 sols/s with my R9 290 with the v5 code in open cl.  0 sols probably because some timeout is causing a crash

**Comment by kruisdraad** [comment]
I ran both versions. 

Setup: 6x GTX1070 with Windows 10 latest drivers, etc (anno vers)

0.4h plain: 241 sol/s power usage 51%
0.4h maxplus: 2.4 sol/s and a near 400 I/s. Also the power usage is above 70%

previsous version got about 250 so its a little less, power usage is much more stable though.

**Comment by maztheman** [comment]
hmm 241 is really not that competitive to the SA linux version, is it?

**Comment by kruisdraad** [comment]
Honestly i havent tried the linux version yet, The zcminer-dev windows version gets about 300 so its not that bad.

You have Linux example on actual speeds?

**Comment by chronosek** [comment]
Compiled. For me crashing after 20 sec (i see constantly increase use of gpu memory till all 4GB is fillup) and then nvidia is in P5 locked state..

[23:00:05][0x000011dc] Using SSE2: YES
[23:00:05][0x000011dc] Using AVX: YES
[23:00:05][0x000011dc] Using AVX2: YES
[23:00:05][0x000011a8] stratum | Starting miner
[23:00:05][0x000011a8] stratum | Connecting to stratum server eu1-zcash.flypool.org:3333
[23:00:05][0x00001194] miner#0 | Starting thread #0 (CUDA-SILENTARMY) GeForce GTX 980 (#0) BLOCKS=64, THREADS=512
[23:00:05][0x000011a8] stratum | Connected!
[23:00:05][0x000011a8] stratum | Subscribed to stratum server
[23:00:05][0x000011a8] miner | Extranonce is fa613f0f55
[23:00:05][0x000011a8] stratum | ←[35mTarget set to 004189374bc6a7ef9db22d0e5604189374bc6a7ef9db22d0e5604189374bc6a7←[0m
[23:00:06][0x000011a8] stratum | ←[36mReceived new job #11ee30962342110c9785←[0m
[23:00:20][0x000011dc] ←[33mSpeed [300 sec]: 8.72074 I/s, 15.646 Sols/s←[0m
[23:00:36][0x000011dc] ←[33mSpeed [300 sec]: 8.94374 I/s, 16.6693 Sols/s←[0m
<error> CUDA error 'out of memory' in func 'sa_cuda_context::solve' line 1029
<error> CUDA error 'out of memory' in func 'sa_cuda_context::solve' line 1030
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1073
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1024
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1025
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1029
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1030
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1073
<error> CUDA error 'unspecified launch failure' in func 'sa_cuda_context::solve' line 1024
[ ... ]

**Comment by maztheman** [comment]
yes, sorry there is a memory "leak" that i already have fixed but not have pushed
Its only supposed to create the 2 buffers once, and reuse the, in my old code I was creating it every time and not deleting....:P

**Comment by auroracoin** [comment]
I tried it on a 750ti  comp 5.0  and I get this massage. Missing file MSVCP140.dll  for win 8.1

**Comment by maztheman** [comment]
oh, you need to install the redist file:
https://www.microsoft.com/en-ca/download/details.aspx?id=48145

**Comment by maztheman** [comment]
@chronosek ive checked in the fixes

**Comment by auroracoin** [comment]
That worked...thx :)

**Comment by chronosek** [comment]
@maztheman thx, not crashing now, but always get 0 sol/s no matter what -cb, -ct will set

**Comment by maztheman** [comment]
Yeah some internal issue, ill have to fully debug it again...

**Comment by dtawom** [comment]
Getting @ 17-18 sol/s with a 1060 3gb card with 0.4h.  I found the best rate for this card is obtained with -cb 128 -ct 32 (autodect puts it at -cb 63 ct 64 and only yields 15 to 16 sol/s.

**Comment by krnlx** [comment]
removing packed atomic counters = bad, I tested it in opencl, it is fastest. I tested packed 64-bit atomics too, 1-2% slower

**Comment by chronosek** [comment]
tpruvot did good job porting to cuda, specially with atomic part (working stable at 58 sol/s but still eqm doing 66 sol/s), i think maztheman problems was from some hardcoded values or other code what was not in silentarmy

**Comment by maztheman** [comment]
I added a test program that will help me debug this cuda issue.  Please post your log files.

**Comment by drigger** [comment]
[log.txt](https://github.com/maztheman/nheqminer/files/593068/log.txt)

**Comment by maztheman** [comment]
I created a new build that should "work" on 1080 and 1070's again.  Probably wont break any records though...

**Comment by drigger** [comment]
Confirmed, it works and even gives a bit better results on my GTX 1080 than all the previous builds.
![image](https://cloud.githubusercontent.com/assets/2197585/20329317/9cf905a0-aba8-11e6-9854-25e4b8c05327.png)
Thank you!

**Comment by chronosek** [comment]
working for gtx980 - got 41 sol/s

**Comment by dtawom** [comment]
Still not working with GTX 580 1.5GB

**Comment by maztheman** [comment]
@dtaworm, can you run the debug tool and post the log?

**Comment by dtawom** [comment]
@maztheman yeah i'll do that tomorrow afternoon when I get into work.

**Comment by auroracoin** [comment]
On CUDA, it doesn't display what cards are doing what hash. :)

**Comment by drigger** [comment]
```
arg 1 = -r
Settings:
NR_ROWS_LOG = 20
OVERHEAD = 6
COLL_DATA_SIZE_PER_TH = 60
Run Count = 100
Device #0 | GeForce GTX 1080 | Running Tests....
Silentarmy V5 test
35.878 sols/s
Silentarmy V4/V5/maztheman mix test
29.643 sols/s
maztheman test
0 sols/s
```

```
arg 1 = -r
Settings:
NR_ROWS_LOG = 20
OVERHEAD = 6
COLL_DATA_SIZE_PER_TH = 60
Run Count = 100
Device #0 | GeForce GTX 580 | Running Tests....
Silentarmy V5 test
18.6791 sols/s
Silentarmy V4/V5/maztheman mix test
30.8821 sols/s
maztheman test
12.5392 sols/s
```

```
arg 1 = -r
Settings:
NR_ROWS_LOG = 20
OVERHEAD = 6
COLL_DATA_SIZE_PER_TH = 60
Run Count = 100
Device #0 | GeForce GTX 550 Ti | Running Tests....
Silentarmy V5 test
<error> cuda error 2, out of memory in function 'context::init', line 1313
context intialization failed
...
0 sols/s
Silentarmy V4/V5/maztheman mix test
<error> cuda error 2, out of memory in function 'context::init', line 1313
context intialization failed
...
0 sols/s
maztheman test
<error> cuda error 2, out of memory in function 'context::init', line 1313
context intialization failed
...
0 sols/s
```

**Comment by maztheman** [comment]
hmm interesting

**Comment by oddin98** [comment]
On my **GeForce GTX 650**
nheqminer -t 0 -cd 0 -cs -b

[15:25:51][0x00000a7c] Using SSE2: YES
[15:25:51][0x00000a7c] Using AVX: NO
[15:25:51][0x00000a7c] Using AVX2: NO
[15:25:51][0x00000a7c] Benchmarking CUDA worker (CUDA-SILENTARMY) GeForce GTX 650 (#0) BLOCKS=14, THREADS=64
[15:25:51][0x00000a7c] Benchmark starting... this may take several minutes, please wait...
[15:26:34][0x00000a7c] Benchmark done!
[15:26:34][0x00000a7c] Total time : 42382 ms
[15:26:34][0x00000a7c] Total iterations: 200
[15:26:34][0x00000a7c] Total solutions found: 374
[15:26:34][0x00000a7c] Speed: 4.71898 I/s
[15:26:34][0x00000a7c] Speed: 8.8245 Sols/s

Is this good? 

UPDATE: tinkering around 

![650](https://cloud.githubusercontent.com/assets/17937548/20367114/b62333dc-ac13-11e6-90cb-2526bc92d364.png)

**Comment by maztheman** [comment]
For a GTX 650, that is what I get.  I havent seen any higher.

**Comment by maztheman** [comment]
We're you able to over clock the card?

Edit: oh I see you have also 2 cpu cores

**Comment by oddin98** [comment]
Noticed after 8 hrs of running or so, it drops speed to 1sol. The has to be
restarted... any info as to why?

**Comment by maztheman** [comment]
Not really, is it possible that your GPU overheated or something?

**Comment by dtawom** [comment]
@maztheman I ran the new debug tool but where is the log file saved?  Is there a switch I need to use to write the log to a text?  I did notice that it gave me @ 18 sol/sec on the v4 and 24 sol/sec on the v5 with the 580.  But with nheqminer using the -cd 0 switch detects the 580 but I'm getting 0 sol/s using the newest 0.4i.

**Comment by maztheman** [comment]
Yeah the debug tool has a little different code I was playing around with. To write the log add 1>run.txt to the end of your command line.  Thst should write all the text to a file.

**Comment by dtawom** [comment]
@maztheman Here ya go, I also included a screenshot of it in regular mode.
[run.txt](https://github.com/maztheman/nheqminer/files/599122/run.txt)
![untitled](https://cloud.githubusercontent.com/assets/23352016/20419788/4c464ea2-ad05-11e6-8fa8-3e084afe3ed6.jpg)

**Comment by chronosek** [comment]
i see you using cuda_tromp for old and gtx 580 what have compute capability 2.0, so i suspect it was not compiled for your card (in sources i see cuda_tromp project set for 2.0+, but restriction on  equi_miner.cu set for 5.0+), try use silentarmy option or wait for maztheman new files

**Comment by dtawom** [comment]
Thanks @chronosek , maybe that will help @maztheman but I have no idea how to compile or change restrictions on equi_miner.cu from 5.0+to 2.0+

**Comment by chronosek** [comment]
If you want try cuda_tromp you could give a try dll compiled by me http://chronx.pl/cuda/cuda_tromp_75.dll (it was for cuda8.0 but still should work with new drivers) but still even without atomic support silentarmy port should be faster http://chronx.pl/cuda/cuda_silentarmy.dll , just replace files and use good options

**Comment by dtawom** [comment]
@chronosek that worked like a champ, getting @ 13 sol/sec which is better than the nothing I was getting before.
Thanks man,

**Comment by dtawom** [comment]
Only get about 45 sol/sec with R9 fury.  According to silentarmy readme I expected to be getting at least the same 115 sol/s of an R9 Nano.
https://github.com/mbevand/silentarmy/commit/503697cd03d68eef9f6824aef920b50999bef4f1?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
![r9](https://cloud.githubusercontent.com/assets/23352016/20425651/f6190588-ad27-11e6-84c7-c5aeec7ba413.jpg)

**Comment by chronosek** [comment]
i think opencl was not updated here to lastest silentarmy

**Comment by maztheman** [comment]
I thought it was under the ocl_silentarmy/gpu/kernel folder. I use ocl with my r 290 and get like 80+ sols/s

**Comment by maztheman** [comment]
ocl_silentarmy/zcash/gpu/kernel.cl

**Comment by dtawom** [comment]
@maztheman are you running under windows or linux enviroment with your 290?  The 115 Sol/s results I've seen are all under linux with a single R9 nano.  Just to make sure it wasn't the machine I moved the fury to another system and got similar results.  I'm barely getting 115 sol/sec with 2x R9 fury and I5-4460 cpu.

**Comment by maztheman** [comment]
Im running under windows environment.  I have the most up to date kernel.cl file and it seems to be working pretty good.  I dont use NiceHashMiner.exe to run nheqminer.exe, I just run it directly.

**Comment by dtawom** [comment]
@maztheman yeah I run directly with nheqminer.exe as well.  The latest kernel.cl file you mention is that included in your most recent 0.4i build or do I need to download that from elsewhere?  The one I have from your latest build is dated 11/10/16 at 11:27 AM.

**Comment by maztheman** [comment]
EDIT: ok i updated the zip file, it has the correct kernel.cl file..

**Comment by dtawom** [comment]
Thanks @maztheman I just messed myself a little.  Getting 110 sol/s off a single r9 now.  Probably gonna double at work now too.

**Comment by maztheman** [comment]
@dtawom , sweet.

**Comment by dtawom** [comment]
Just wanted to say thanks @maztheman . With your help I'm about 1/2 way down on page 1 at https://zcash.nicehash.com/workers with 340 sol/sec between all the systems at work and home (7) without disrupting normal usage much. I'm working on getting one more up and running which should put me at @ 400.  I wish our server had a pci-e x16 slot, might even be able to push 450 if it did.  Anyway, you're awesome. If you're ever in Alaska and want a tablet, laptop, or desktop I'll hook you up :)  Do you take donations?  Thanks to you too @chronosek , you're cuda 2.0 dll added about 20 sol/sec to the total.

**Comment by maztheman** [comment]
Well I'm glad you got all that working!  I live in Canada so I'm pretty
close heh.  I have a btc address 18KXbLfgVt9zLxEuboPCmjpuvLL7VtjPhm if you
wanted to donate.

Maztheman

**Comment by dtawom** [comment]
I don't know what changed in the recent builds of silentarmy, but I'm getting about triple the sol/s out of my 1060 with this win build https://github.com/zawawawa/silentarmy/releases .  I think I was getting @ 25 sol/s with your latest build, I'm getting 85-95 on zawawawa's.  CPU mining doesn't appear to work on his and I get virtually identical sol/s on all AMD card's I've tried.  FYI I have no bitcoins nor do I have any idea how to donate to a btc address, I was hoping for something like a paypal address or a site you have with a donate button or something.

**Comment by maztheman** [comment]
I'll have a look at this guy's mods.

**Comment by maztheman** [comment]
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=69GMVEPYDMBJJ"><img src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!" ></a>
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">

**Comment by maztheman** [comment]
I have posted a new release that needs to be tested.  Supposed to increase GTX 10XX series cards by a lot.

maztheman

**Comment by kruisdraad** [comment]
ill do that now

**Comment by kruisdraad** [comment]
it doesnt seem to actually start to mine. it takes 30% of each GPU and just 'sits' there. No output after 'autherized worker'

without CS it does start, but very poor rate

with CS it either just hangs, disabled firewall and after 2 new job messages it just 'stops' without any output.

testing again with G version which works fine and i copied that start.bat from that version so it would work on K version soon.

**Comment by maztheman** [comment]
Can you try "-b 200 -t 0 -cs -cd 0"

**Comment by kruisdraad** [comment]
same thing:
Setting log level to 2
[23:23:22][0x000017f0] Using SSE2: YES
[23:23:22][0x000017f0] Using AVX: NO
[23:23:22][0x000017f0] Using AVX2: NO
[23:23:23][0x000017f0] Benchmarking CUDA worker (CUDA-SILENTARMY) GeForce GTX 1070 (#0) BLOCKS=105, THREADS=64
[23:23:23][0x000017f0] Benchmark starting... this may take several minutes, please wait...

and then just console again after 2/3 secs

**Comment by maztheman** [comment]
Im about to upload a new binary v0.4k_2.7z that should hopefully do something for you :)

**Comment by dtawom** [comment]
Getting a bit better sol rate on my dual R9 Fury's and I5-4460 system.  Took a bit longer to ramp up but seems to be much more consistent rate of @ 235-245 sols/s.  With last build it would flux anywhere from 180-240.  I'll post my 1060 results in a bit.

**Comment by maztheman** [comment]
1080 can do 107 sols/s, 970 can do 73 sols/s

**Comment by dtawom** [comment]
I'm only getting 20 sol/s with my 1060 on this new build, about the same as I was getting before.

**Comment by auroracoin** [comment]
maztheman I'm getting 60 s/s with nicehash's miner with a nvidia 750ti on windows 8.1. On my windows vista the first release 11 s/s because i can't load msvs 2015. Is it possible to make 1 build that doesn't use msvs 2015.  error says missing 140.dll. I'm mining at nicehash selling my hash. And I cant compile. Would like to try your latest release for cuda too. thx  :)

**Comment by kruisdraad** [comment]
@maztheman with v2 same issue, wont start mining with -cs

**Comment by maztheman** [comment]
@kruisdraad im not sure what the issue could be...other people have successfully ran it...?

**Comment by oufeipho** [comment]
WIN10
gtx1070
-cs no work

**Comment by kruisdraad** [comment]
@maztheman perhaps driver issue, what are they running?

**Comment by maztheman** [comment]
NV 375.95

**Comment by kruisdraad** [comment]
I am on the 372.90 which is somewhat more stable and works fine with devminer and eqm

**Comment by maztheman** [comment]
Since the older cards were having not great success with V5, I created a mix and match of v4 and v5 for older compute 30, 20 devices.  Also with the new build CUDA SA is the default, so its a direct drop in replacement for nice hash miner.

**Comment by dtawom** [comment]
What's going on, are servers down? https://zcash.nicehash.com/workers shows no workers and I'm getting failed connections on stratum.zcash.nicehash.com:3357 and the couple other servers I've tried to connect to.

**Comment by maztheman** [comment]
https://zcash.nicehash.com

Looks like the zcash pool is done.  There are other zcash pools however.

**Comment by dtawom** [comment]
Yeah I figured that out, switched to the more popular flypool for mining.  Guess there's a smaller chance of it just going TU.

Thanks,

**Comment by jddebug** [comment]
@dtawom What area of Alaska? (Anchorage here)

**Comment by drigger** [comment]
**v0.4l** works with GTX 650 and gives me **~5** Sols/s on CUDA `-t 0 -cd 0`==`-t 0 -cd 0 -cv 1`==`-t 0 -cd 0 -cs` and **~3** Sols/s on OCL `-t 0 -od 0`...
However, it was giving me **~8** Sols/s on OCL `-t 0 -od 0` not while ago w/ **v0.4g** ;)
Also, **v0.4l** doesn't work on CUDA at all on GTX 550 Ti and GTX 580:

`-t 0 -cd 0`:
- <error> CUDA error 'invalid device symbol' in func 'sa_cuda_context::solve' line 2477

`-t 0 -cd 0 -cs`:
- <error> CUDA error 'invalid device symbol' in func 'sa_cuda_context::solve' line 2477

`-t 0 -cd 0 -cv 0`:
- <error> CUDA error 'unknown error' in func 'sa_cuda_context::sa_cuda_context' line 2328

`-t 0 -cd 0 -cv 1`:
- <error> CUDA error 'invalid device ordinal' in func 'cuda_sa_solver::getinfo' line 37


GTX 550Ti was tested @**W10 14393.223 NV 375.70**
GTX 580 was tested @**W10 14393.447  NV 375.95**

**Comment by maztheman** [comment]
@drigger for the older cards did you rename the cuda_silentarmy_sm30.dll ? I basically rolled back most changes for that DLL.

**Comment by drigger** [comment]
LOL, missed that part about renaming completely, my bad, sorry)

**Comment by maztheman** [comment]
I'm trying to incorporate some of the newer enhancements into the older 3.0 cards.  I'm hoping the next build will be a performance increase.

**Comment by drigger** [comment]
For a reference, this is what I get with renamed dll on v0.4l @**CUDA_SA**:

- GTX 550 Ti: ~4 Sols/s
- GTX 580: ~28 Sols/s
- GTX 650: ~9 Sols/s

There is a small loss for 550Ti in comparison with standalone SA miner (4 vs 8), but for 580 & 650 it is a small win (28 vs 23, 9 vs 8), so definitely thank you for this release ;)

**Comment by maztheman** [comment]
I made a special build for old cuda cards:
https://github.com/maztheman/nheqminer/releases/tag/v0%2C4m_Beta

I get 1 more sols/s on my GTX 650 so almost 10%?

let me know what you get.

**Comment by oufeipho** [comment]
@maztheman 
WIN10 
375.95
GTX1070
v0.4l
![image](https://cloud.githubusercontent.com/assets/6495968/20642808/4124b206-b454-11e6-81d7-f429afe09252.png)
Why?

**Comment by maztheman** [comment]
Hmm I don't know but maybe something to do with no Avx?

**Comment by jddebug** [comment]
@maztheman 

Heres my t32 with your newest beta. I'll try the others here soon.

20 sols on a gtx760

https://puu.sh/svlKV/e9d0b41f6e.png

btw, the old t32 from yesterday benchmarks at 15.18 sols as a comparison.

**Comment by jddebug** [comment]
So....

t32
20.32 sols on gtx760
https://puu.sh/svn3p/95b630c10b.png

t64
18 sols on gtx760
https://puu.sh/svmaW/70c1bc16ed.png

t128
16 sols on gtx760
https://puu.sh/svmpa/4b347bdeb1.png

t256
14.25 sols on gt760
https://puu.sh/svmGD/3ebe13830b.png

Maybe you can make a t16?

**Comment by jddebug** [comment]
Seems with the t32 its using an additional 18 watts so 138 watts for a gtx760 at 20 sols. Thats probably to expensive to actually use to mine unless free electricity which I do not have but a great improvement. Good job maztheman

Real world mining its seeing about 19.5 sols

**Comment by maztheman** [comment]
I uploaded a 16 thread version

**Comment by maztheman** [comment]
Thanks for your testing!  Not exactly what I was expecting but seems each card has its own sweet spot.

**Comment by jddebug** [comment]
t16
16.5 sols on gtx760
So far seems the 32 is the best.

Whenever I start the miner it always shows blocks 42 and threads 64. Is that when the mining software thinks I should be using?

**Comment by maztheman** [comment]
The original miner used that information but I dont use it. 

42 is 7 * your sm count, which I guess is 6.  It seems silent army uses a different block dimension so that it can use the thread id as an index into the hash table.

**Comment by drigger** [comment]
My results with latest beta:

GTX 580:

- t16 22.41
- t32 27.5
- **t64 32.3**
- t128 29.5
- t256 26

GTX 550 Ti:

- t16 5.7
- t32 7.4
- **t64 7.5**
- t128 6.5
- t256 5.4

GTX 650:

- t16 5.3
- t32 6.6
- **t64 8.8**
- t128 8.6
- t256 8.0

**Comment by maztheman** [comment]
@drigger. Thanks for the testing.

**Comment by Kahana82** [comment]
I'm getting around 100 sols with GTX980 with version L now
best result (102 sols) with -cs -cb 512 -ct 64 -cd 0

with cpu (7 out of 8 threads) it gives around 120 sols
 -t 7 -cs -cb 512 -ct 64 -cd 0
I found keeping 1 thread free (7 of 8 total) gives better result on gpu and same if not better final sols.

On previous versions (i) best (42 sols) was -cs -cb 256 -ct 32 -cd 0
around 66 sols with -t7 -cs -cb 256 -ct 32 -cd 0

This is a huge improvement ! keep up the good work Maz :)

**Comment by maztheman** [comment]
Tnx I'll keep porting any enhancements I find.

**Comment by dtawom** [comment]
@jddebug Kenai/Soldotna area.  Thanks for the updates @maztheman, I'll post updates for all my stuff tomorrow.

**Comment by ceozero** [comment]
Can you please send me a private generation absenteeism?

**Comment by maztheman** [comment]
@ceozero Sorry I dont understand what you mean...

**Comment by ceozero** [comment]
@maztheman I need a new miner. You need to modify the code to re compile. can you do it?

**Comment by maztheman** [comment]
Yeah I can compile anything for windows.

**Comment by ceozero** [comment]
May I know your email address? Or do you want to send a mail to me.     ceozero@me.com

**Comment by maztheman** [comment]
I sent you an email

**Comment by dtawom** [comment]
Getting @ 75-85 sol/sec off my GTX 1060 3GB with 0.4l, for some reason that number doesn't improve much when I have all 4 CPU's running too.  I was getting better results using your miner for CPU and Silentarmy for GPU at a combined 100 sol/s.  Default detection for the 1060 is 63 blocks & 64 threads, I cap out at about 75 with this setting, 128b and 32t seems to give me the best capping out at about 85 sol/sec.  Is there a calculator out there that will tell you what the best block and thread count is for any given model and ram size video cuda card?

**Comment by ceozero** [comment]
I can't run, I'm still working on that.

**Comment by maztheman** [comment]
@dtawom , the silentarmy does not include some of the changes I added, so it maybe more efficient for that specific card.  unless you are using the https://github.com/zawawawa/silentarmy version.  I ported those changes and some other nvidia specific parameters and stuff.  If I had all the nvidia cards I would be testing and testing before I created builds.  I just have to trust that the changes im porting "work" and "work well" with all nvidia 10xx series cards.  There is a "Version 6" of silentarmy coming VERY soon.  I will be porting those changes ASAP.  

Stay tuned...

**Comment by dtawom** [comment]
@maztheman yeah the zawawawa one is the one I was using.  The difference is so negligible (5-10 sol/sec per machine) that it is easier just to use your latest build only.  The new nvidia one  you made for older cards is getting me @ 40 sol/s on my 580 gtx which is @ 15 more sol/sec than I was getting before.  Thanks soo much for the updates, they've got me hitting peaks of  650 sol/s now between all my rigs.  Looking forward to silentarmy V6, hope the improvements are as significant as they were from 4 to 5.

**Comment by maztheman** [comment]
I'm just glad the work I'm doing is useful to someone :-)

**Comment by ceozero** [comment]
@maztheman what‘s  time update.  to Faster.,

**Comment by maztheman** [comment]
A few more days

**Comment by dtawom** [comment]
I dunno if this guy is running off silentarmy v6 or something else, but these numbers are soooo sexy.  Gonna give um a try on my 1060 rigs.  https://forum.z.cash/t/ewbfs-nvidia-cuda-zcash-miner-1060-170-h-s-gtx-1070-250-h-s/12523

**Comment by maztheman** [comment]
Oh it's closed source so I can't see what he is doing. I can profile the exe probably and see what I can see

**Comment by dtawom** [comment]
Confirmed 175 sol/sec on 1060 with no CPU.  You should do what this guy does and take a couple percent for yourself.  I'd rather support you than him.

**Comment by dtawom** [comment]
Holy moly, getting triple speed off my R9 Fury's now with claymore.  325 H/s per card with https://github.com/nanopool/ClaymoreZECMiner
Gonna break the gigahash mark per sec tomorrow :)

**Comment by maztheman** [comment]
:) wow, looks like claymore is on top again!

**Comment by maztheman** [comment]
Looks like an update will happen pretty soon...

**Comment by maztheman** [comment]
new build new thread

https://github.com/maztheman/nheqminer/issues/8
