### ISSUE TITLE
no msvs 2015

### ISSUE THREAD

**Issue by auroracoin** [maztheman/nheqminer#6]
maztheman I'm getting 60 s/s with nicehash's miner with a nvidia 750ti on windows 8.1. On my windows vista the first release 11 s/s because i can't load msvs 2015. Is it possible to make a build that doesn't use msvs 2015 error says missing 140.dll. I'm mining at nicehash selling my hash. And I cant compile. Would like to try your latest release for cuda. thx  :)

**Comment by maztheman** [comment]
Please download and install this redistribution:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

It is available for Windows 8.1.  I use 2015 because of the compiler enhancements.

**Comment by auroracoin** [comment]
Thank you but windows VISTA 64x won't install 2015. The problem is I can't get Windows Vista Service Pack 2 installed to install 2015. I get an error code because of a missing file I can't find.

**Comment by maztheman** [comment]
Okay, Ill see about putting up a vs 2012 version.

**Comment by maztheman** [comment]
I hope this works for you:

https://github.com/maztheman/nheqminer/releases/download/v0.4l/v0.4l_vs120.7z

**Comment by auroracoin** [comment]
Thx But the last driver was 5-2016 and it's saying it won't work with that driver. Almost have it. :)   http://i.imgur.com/c0OiKO1.jpg

**Comment by maztheman** [comment]
oh because im using CUDA 8.0 ?

**Comment by maztheman** [comment]
Okay try this instead!, cuda 7.5, visual studio 2013:

https://github.com/maztheman/nheqminer/releases/download/v0.4l/v0.4l_vs120_cuda75.7z

**Comment by auroracoin** [comment]
Says now I need cudart64_80.dll

**Comment by maztheman** [comment]
cudart60_80.dll or cudart64_80.dll ?

**Comment by auroracoin** [comment]
cudart64_80.dll

**Comment by maztheman** [comment]
get it here:

https://github.com/maztheman/nheqminer/releases/download/v0.4l/cudart64_80.dll

**Comment by auroracoin** [comment]
nheqminer.exe      -u wallet.VISTA  -p x  -cd 0 1  is this the right bat file?  so many different miner apps.  It opens then almost starts hashing then closes.

**Comment by maztheman** [comment]
try doing a cuda query first:
nheqminer.exe -ci

then benchmark the devices by:
nheqminer.exe -b 25 -t 0 -cd 0

where "0" is the device id listed in the cuda query.

**Comment by auroracoin** [comment]
ok trying  thank you
sm 5.0  and count 5  trying next command   crash

http://i.imgur.com/OzmJQqn.jpg

**Comment by auroracoin** [comment]
crash using only this   nheqminer.exe -b 25 -t 0 -cd 0

**Comment by maztheman** [comment]
oh hmm....I dont know what else to try, im not sure how to get this to work as I dont have any Vista installs.

**Comment by auroracoin** [comment]
at this point it maybe my bat file?  commands

**Comment by maztheman** [comment]
I dont think so, if its crashing just benchmarking I would need to see the screen shot of the crash, as it might help me figure out why its happening...

**Comment by auroracoin** [comment]
ok  trying to grab it with this      nheqminer.exe -b 25 -t 0 -cd 0

**Comment by auroracoin** [comment]
http://i.imgur.com/omqpo5G.jpg

**Comment by auroracoin** [comment]
then crashes

**Comment by auroracoin** [comment]
for comparison or info here is nicehashs first miner i think or ?    http://i.imgur.com/9j5TcIY.jpg
hashrate should be about 65 s/s per card.

**Comment by auroracoin** [comment]
with this command it almost starts hashing.
nheqminer.exe      -u wallet.VISTA   -p x  -cd 0 1  -t 0

**Comment by auroracoin** [comment]
If this helps this is a pic of files of yours and the one that works with 2 cards at very low hashrates.
http://i.imgur.com/RcDZ98m.jpg
tpruvot did the one that works, but at very very low hashrates. 11 s/s on one card. Should be closer to 50-60 s/s per card. Thx :)
